### ISSUE TITLE
Teensy 3.x Boards have embedded MAC.

### ISSUE THREAD

**Issue by csobsidian** [mrrees/MegaPixelController#2]
There should be no need to issue a specific MAC to each controller since PJRC has an IEEE OUI and has embedded a unique MAC adress into each Teensy 3.x board. Instructions on retrieving that address can be found [here](https://forum.pjrc.com/threads/91-teensy-3-MAC-address).

**Comment by mrrees** [comment]
This statement is true if purchasing chips from PJRC however Virgin Chips lack the IEEE OUI and will require MAC to be specified
